### ISSUE TITLE
Add simple GET method

### ISSUE THREAD

**Issue by zkzofn** [zkzofn/art_archive#6]
GET method 기능 간단히 구현

**Comment by phs1919** [comment]
issue를 조금 더 구체적으로 쓰시면 리뷰할 때 더 잘 알 수 있을거 같아요! 예를 들어, 현재는 어떠한 endpoint 인지, request시 parameter들은 어떠한게 들어갈 수 있는지, response는 어떻게 나오는지 등의 정보가 있으면 좋을거 같습니다

**Comment by zkzofn** [comment]
넵 참고해서 작성하겠습니다.
